#!/bin/bash

# read text symbols from libclang_rt.asan*.so files and
# update the map files accordingly.

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <prebuilt_dir>, where prebuilt_dir is one of clang-<version> directories here"
    exit 1
fi

prebuilt_dir=$1

asan_libs=`find $prebuilt_dir -name "libclang_rt.asan*-android.so"`

for lib in $asan_libs
do
map_file=`basename $lib | sed 's/\.so/\.map\.txt/'`
echo Updating $map_file
nm -g --defined-only $lib | \
  awk 'BEGIN { print "# AUTO-GENERATED by update_map_files.sh. DO NOT EDIT.\nLIBCLANG_RT_ASAN {\n  global:"}\
       {if ($2 == "T" || $2 == "W" || $2 == "B") {printf "    %s;\n",$3}}\
       END { print "  local:\n    *;\n};"}'\
  > $map_file
done
echo Done.
